---
- name: Download Tomcat using unarchive
  become: yes
  unarchive:
    src: "{{download_url}}"
    dest: /opt/tomcat8
    mode: 0755
    remote_src: yes
    group: tomcat
    owner: tomcat
    
 
- name: Move files to the /opt/tomcat8 directory
  become: yes
  copy:
     src: /opt/tomcat8/apache-tomcat-8.5.84/
     dest: /opt/tomcat8/
     mode: 0755
     owner: tomcat
     group: tomcat
     mode: "u+rwx,g+rx,o=rx"
     recurse: yes
     
- name: Remove apache directory
  file:
     path: /opt/tomcat8/apache-tomcat-8.5.84/
     state: absent