---
- hosts: localhost
  connection: local
  tasks:
    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - apache2
        - ufw
        - mysql
