---
- hosts: localhost
  connection: local
  tasks:
     - name: install pakages withitems
       yum:
         name: "{{ items }}"
         status: absent
       with_items:
          - httpd
          - tree
