---
- hosts: localhost
  connection: local
  tasks:
     - name: install pakages withitems 
       yum: 
         name: "{{ items }}"
         state: present         
   	   with_items:
          - apache2
          - ufw