---
# handlers file for tomcat
- name: Reload the SystemD to re-read configurations
  become: yes
  systemd:
     daemon-reload: yes

- name: Enable the tomcat service and start
  become: yes
  systemd:
     name: tomcat
     enabled: yes
     state: started

- name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
  tags: test
  uri:
    url: http://localhost:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10